### ISSUE TITLE
pydantic_core._pydantic_core.ValidationError: 1 validation error for typed-dict

### ISSUE THREAD

**Issue by Pan06da** [severian42/GraphRAG-Local-UI#20]
🚀 Reading settings from ragtest/settings.yaml

Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/Users/leioupan/GraphRAG-Ollama-UI/graphrag/index/__main__.py", line 76, in <module>

    index_cli(

  File "/Users/leioupan/GraphRAG-Ollama-UI/graphrag/index/cli.py", line 97, in index_cli

    pipeline_config: str | PipelineConfig = config or _create_default_config(

                                                      ^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/leioupan/GraphRAG-Ollama-UI/graphrag/index/cli.py", line 235, in _create_default_config

    parameters = _read_config_parameters(root, config, reporter)

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/leioupan/GraphRAG-Ollama-UI/graphrag/index/cli.py", line 274, in _read_config_parameters

    return create_graphrag_config(data, root)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/leioupan/GraphRAG-Ollama-UI/graphrag/config/create_graphrag_config.py", line 70, in create_graphrag_config

    InputModelValidator.validate_python(values, strict=True)

  File "/Users/leioupan/graphrag-ollama/lib/python3.11/site-packages/pydantic/type_adapter.py", line 142, in wrapped

    return func(self, *args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/leioupan/graphrag-ollama/lib/python3.11/site-packages/pydantic/type_adapter.py", line 373, in validate_python

    return self.validator.validate_python(object, strict=strict, from_attributes=from_attributes, context=context)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

pydantic_core._pydantic_core.ValidationError: 1 validation error for typed-dict

local_search

  Input should be a valid dictionary [type=dict_type, input_value='None', input_type=str]

    For further information visit https://errors.pydantic.dev/2.8/v/dict_type

**Comment by severian42** [comment]
Hey! I have been unable to reproduce this error on my end. Could it have to do with the system you are running? It seems Windows has had some issues with the graphRAG stuff for other users. I only have Mac so I haven't been able to debug other OS environments at all yet. Feel free to share as much info about your issue and I'll see if I can help debug
