### ISSUE TITLE
indexing gets error

### ISSUE THREAD

**Issue by kksasa** [severian42/GraphRAG-Local-UI#27]
Sys - WIN10
---------

Traceback (most recent call last):

  File "C:\Users\LLM\fast_api\installer_files\env\lib\runpy.py", line 196, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "C:\Users\LLM\fast_api\installer_files\env\lib\runpy.py", line 86, in _run_code

    exec(code, run_globals)

  File "C:\Users\LLM\fast_api\GraphRAG-Ollama-UI\graphrag\index\__main__.py", line 76, in <module>

    index_cli(

  File "C:\Users\LLM\fast_api\GraphRAG-Ollama-UI\graphrag\index\cli.py", line 97, in index_cli

    pipeline_config: str | PipelineConfig = config or _create_default_config(

  File "C:\Users\LLM\fast_api\GraphRAG-Ollama-UI\graphrag\index\cli.py", line 235, in _create_default_config

    parameters = _read_config_parameters(root, config, reporter)

  File "C:\Users\LLM\fast_api\GraphRAG-Ollama-UI\graphrag\index\cli.py", line 269, in _read_config_parameters

    reporter.success(f"Reading settings from {settings_yaml}")

  File "C:\Users\LLM\fast_api\GraphRAG-Ollama-UI\graphrag\index\progress\rich.py", line 135, in success

    self._console.print(f"\U0001f680 [green]{message}[/green]")

  File "C:\Users\LLM\fast_api\installer_files\env\lib\site-packages\rich\console.py", line 1673, in print

    with self:

  File "C:\Users\LLM\fast_api\installer_files\env\lib\site-packages\rich\console.py", line 865, in __exit__

    self._exit_buffer()

  File "C:\Users\LLM\fast_api\installer_files\env\lib\site-packages\rich\console.py", line 823, in _exit_buffer

    self._check_buffer()

  File "C:\Users\LLM\fast_api\installer_files\env\lib\site-packages\rich\console.py", line 2027, in _check_buffer

    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))

  File "C:\Users\LLM\fast_api\installer_files\env\lib\site-packages\rich\_windows_renderer.py", line 19, in legacy_windows_render

    term.write_text(text)

  File "C:\Users\LLM\fast_api\installer_files\env\lib\site-packages\rich\_win32_console.py", line 403, in write_text

    self.write(text)

UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f680' in position 0: illegal multibyte sequence

**Comment by severian42** [comment]
Hey! Thanks for your patience on this, the latest update should take care of this issue. Let me know if you're still having problems after the update! Make sure to clear everything out and start fresh if possible for the best chances of it working immediately. Thanks again for checking out the project!

**Comment by delbern310** [comment]
this problem still exists,how to sovled it ?
