### ISSUE TITLE
Indexing error

### ISSUE THREAD

**Issue by bzhanghh** [severian42/GraphRAG-Local-UI#29]
Traceback (most recent call last):

  File "/usr/lib64/python3.9/runpy.py", line 188, in _run_module_as_main

    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)

  File "/usr/lib64/python3.9/runpy.py", line 147, in _get_module_details

    return _get_module_details(pkg_main_name, error)

  File "/usr/lib64/python3.9/runpy.py", line 111, in _get_module_details

    __import__(pkg_name)

  File "/home/bzhang/GraphRAG-Ollama-UI/graphrag/index/__init__.py", line 6, in <module>

    from .cache import PipelineCache

  File "/home/bzhang/GraphRAG-Ollama-UI/graphrag/index/cache/__init__.py", line 6, in <module>

    from .json_pipeline_cache import JsonPipelineCache

  File "/home/bzhang/GraphRAG-Ollama-UI/graphrag/index/cache/json_pipeline_cache.py", line 9, in <module>

    from graphrag.index.storage import PipelineStorage

  File "/home/bzhang/GraphRAG-Ollama-UI/graphrag/index/storage/__init__.py", line 6, in <module>

    from .blob_pipeline_storage import BlobPipelineStorage, create_blob_storage

  File "/home/bzhang/GraphRAG-Ollama-UI/graphrag/index/storage/blob_pipeline_storage.py", line 14, in <module>

    from datashaper import Progress

  File "/home/bzhang/.local/lib/python3.9/site-packages/datashaper/__init__.py", line 35, in <module>

    from .execution import ExecutionNode, VerbDefinitions, derive_from_rows, parallelize

  File "/home/bzhang/.local/lib/python3.9/site-packages/datashaper/execution/__init__.py", line 1, in <module>

    from .derive_from_rows import derive_from_rows

  File "/home/bzhang/.local/lib/python3.9/site-packages/datashaper/execution/derive_from_rows.py", line 5, in <module>

    from datashaper.execution.utils import transform_pandas_table

  File "/home/bzhang/.local/lib/python3.9/site-packages/datashaper/execution/utils/__init__.py", line 1, in <module>

    from .pandas import transform_pandas_table

  File "/home/bzhang/.local/lib/python3.9/site-packages/datashaper/execution/utils/pandas.py", line 7, in <module>

    from datashaper.execution.utils.parallelize import parallelize

  File "/home/bzhang/.local/lib/python3.9/site-packages/datashaper/execution/utils/parallelize.py", line 17, in <module>

    num_threads: int | None = None,

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by severian42** [comment]
Hey! Thanks for your patience on this, the latest update should take care of this issue. Let me know if you're still having problems after the update! Make sure to clear everything out and start fresh if possible for the best chances of it working immediately. Thanks again for checking out the project!

**Comment by bzhanghh** [comment]
@severian42 Hey thanks for your feedback. I used "python app.py" instead of "gradio app.py" and it worked.
