### ISSUE TITLE
KeyError: "['clustered_graph'] not in index"

### ISSUE THREAD

**Issue by gaostar123** [severian42/GraphRAG-Local-UI#38]
Traceback (most recent call last):
  File "/home/gaoshida/gsd/GraphRAG-Local-UI/graphrag/index/run.py", line 357, in run_pipeline
    result = await workflow.run(context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaoshida/anaconda3/envs/ollama/lib/python3.11/site-packages/datashaper/workflow/workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaoshida/anaconda3/envs/ollama/lib/python3.11/site-packages/datashaper/workflow/workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaoshida/anaconda3/envs/ollama/lib/python3.11/site-packages/datashaper/engine/verbs/select.py", line 25, in select
    output = cast(Table, input_table[columns])
                         ~~~~~~~~~~~^^^^^^^^^
  File "/home/gaoshida/anaconda3/envs/ollama/lib/python3.11/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaoshida/anaconda3/envs/ollama/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/gaoshida/anaconda3/envs/ollama/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['clustered_graph'] not in index"

**Comment by Ikaros-521** [comment]
same

**Comment by m358807551** [comment]
same

**Comment by severian42** [comment]
Hey! Thanks for your patience on this, the latest update should take care of this issue. Let me know if you're still having problems after the update! Make sure to clear everything out and start fresh if possible for the best chances of it working immediately. Thanks again for checking out the project!
