### ISSUE TITLE
ERROR Error executing verb "derive" in create_final_entities: derive() missing 3 required positional arguments: 'column1', 'column2', and 'operator'

### ISSUE THREAD

**Issue by Ikaros-521** [severian42/GraphRAG-Local-UI#44]
```
00:05:29,978 datashaper.workflow.workflow INFO executing verb derive
00:05:29,978 datashaper.workflow.workflow ERROR Error executing verb "derive" in create_final_entities: derive() missing 3 required positional arguments: 'column1', 'column2', and 'operator'
Traceback (most recent call last):
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\datashaper\workflow\workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
TypeError: derive() missing 3 required positional arguments: 'column1', 'column2', and 'operator'
00:05:29,979 graphrag.index.reporting.file_workflow_callbacks INFO Error executing verb "derive" in create_final_entities: derive() missing 3 required positional arguments: 'column1', 'column2', and 'operator' details=None
00:05:29,979 graphrag.index.run ERROR error running workflow create_final_entities
Traceback (most recent call last):
  File "F:\GraphRAG-Ollama-UI\graphrag\index\run.py", line 357, in run_pipeline
    result = await workflow.run(context, callbacks)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\datashaper\workflow\workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\datashaper\workflow\workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
TypeError: derive() missing 3 required positional arguments: 'column1', 'column2', and 'operator'
00:05:29,979 graphrag.index.reporting.file_workflow_callbacks INFO Error running pipeline! details=None
```

**Comment by severian42** [comment]
Hey! Thanks for your patience on this, the latest update should take care of this issue. Let me know if you're still having problems after the update! Make sure to clear everything out and start fresh if possible for the best chances of it working immediately. Thanks again for checking out the project and for your contributions, it is very much appreciated. Feel free to keep sending suggestions and PRs that you find useful

**Comment by Ikaros-521** [comment]
> Hey! Thanks for your patience on this, the latest update should take care of this issue. Let me know if you're still having problems after the update! Make sure to clear everything out and start fresh if possible for the best chances of it working immediately. Thanks again for checking out the project and for your contributions, it is very much appreciated. Feel free to keep sending suggestions and PRs that you find useful

Oh, that's great. I'll try updating the test tomorrow
