### ISSUE TITLE
Error executing verb "cluster_graph" in create_base_entity_graph: Columns must be same length as key

### ISSUE THREAD

**Issue by sdx0112** [severian42/GraphRAG-Local-UI#51]
Hi, I have pulled the latest version and encountered the following error:

09:21:37,332 datashaper.workflow.workflow ERROR Error executing verb "cluster_graph" in create_base_entity_graph: Columns must be same length as key
Traceback (most recent call last):
  File "D:\miniforge3\envs\graphrag\Lib\site-packages\datashaper\workflow\workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\GPT\GraphRAG-Local\GraphRAG-Local-UI\graphrag\index\verbs\graph\clustering\cluster_graph.py", line 102, in cluster_graph
    output_df[[level_to, to]] = pd.DataFrame(
    ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "D:\miniforge3\envs\graphrag\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "D:\miniforge3\envs\graphrag\Lib\site-packages\pandas\core\frame.py", line 4341, in _setitem_array
    check_key_length(self.columns, key, value)
  File "D:\miniforge3\envs\graphrag\Lib\site-packages\pandas\core\indexers\utils.py", line 390, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
09:21:37,383 graphrag.index.reporting.file_workflow_callbacks INFO Error executing verb "cluster_graph" in create_base_entity_graph: Columns must be same length as key details=None
09:21:37,383 root ERROR Error running workflow create_base_entity_graph: Columns must be same length as key
09:21:37,555 graphrag.index.run INFO Running workflow: create_final_entities...
09:21:37,556 graphrag.index.run INFO dependencies for create_final_entities: ['create_base_entity_graph']
09:21:37,558 graphrag.index.run ERROR error running workflow create_final_entities
Traceback (most recent call last):
  File "D:\Projects\GPT\GraphRAG-Local\GraphRAG-Local-UI\graphrag\index\run.py", line 320, in run_pipeline
    await inject_workflow_data_dependencies(workflow)
  File "D:\Projects\GPT\GraphRAG-Local\GraphRAG-Local-UI\graphrag\index\run.py", line 256, in inject_workflow_data_dependencies
    table = await load_table_from_storage(f"{id}.parquet")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\GPT\GraphRAG-Local\GraphRAG-Local-UI\graphrag\index\run.py", line 242, in load_table_from_storage
    raise ValueError(msg)
ValueError: Could not find create_base_entity_graph.parquet in storage!
09:21:37,570 graphrag.index.reporting.file_workflow_callbacks INFO Error running pipeline! details=None

**Comment by sdx0112** [comment]
I looked into the cluster_graph.py code. Here is the code causing the issue from line 102:
```
    output_df[[level_to, to]] = pd.DataFrame(
        output_df[to].tolist(), index=output_df.index
    )
```
The left side has two columns while the right side has only one column.

**Comment by sdx0112** [comment]
I also printed out the output_df. Seems it has only one row, and only the first column 'entity_graph' has value.
![image](https://github.com/user-attachments/assets/473f6534-1962-499c-9bf2-e17aabbed295)

**Comment by myyourgit** [comment]
> I looked into the cluster_graph.py code. Here is the code causing the issue from line 102:
> 
> ```
>     output_df[[level_to, to]] = pd.DataFrame(
>         output_df[to].tolist(), index=output_df.index
>     )
> ```
> 
> The left side has two columns while the right side has only one column.

So how to resolve this issue?
Thanks

**Comment by gaostar123** [comment]
#### I have the same problem

**Comment by JamesCanniffe** [comment]
I'm also getting the same issue when I run this code locally, but not when I run it on google colab.

**Comment by severian42** [comment]
Hey! I've been diving into this, seems to have to do with the way the models are being called with the cache functions. This is part of the library itself and so I'm trying to figure out a better way to handle it locally. Right now it seems like clearing the cache in the indexing dir you initialize helps the issue. Still going to keep working on making this more stable and a non-issue. Thanks for your patience!

**Comment by KDD2018** [comment]
I'm getting the same issue!
And I tried to clean the cache in the indexing dir, it did not work.

**Comment by shijiahao314** [comment]
> I am getting the same issue! And I tried to clean the cache in the indexing dir, it did not work. And then I tried to excute 'python -m graphrag.index --init --root ./indexing/', it raised another error: ValueError: Project already initialized at indexing. So how to resolve it?

Command `python -m graphrag.index --init --root ./indexing` will create `.env` and `settings.yaml` in floder `./indexing`.

If you already have those two files, it will raise error: `ValueError: Project already initialized at indexing`.

Use `python -m graphrag.index --root ./indexing` to run the indexing.
