### ISSUE TITLE
Visualize Graph Error: AttributeError: 'tuple' object has no attribute '__module__'. Did you mean: '__mul__'?

### ISSUE THREAD

**Issue by Ikaros-521** [severian42/GraphRAG-Local-UI#62]
```
Traceback (most recent call last):
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\gradio\blocks.py", line 1907, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\gradio\blocks.py", line 1730, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\gradio\components\plot.py", line 138, in postprocess
    elif "bokeh" in value.__module__:
AttributeError: 'tuple' object has no attribute '__module__'. Did you mean: '__mul__'?
Traceback (most recent call last):
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\gradio\blocks.py", line 1907, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\gradio\blocks.py", line 1730, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\gradio\components\plot.py", line 138, in postprocess
    elif "bokeh" in value.__module__:
AttributeError: 'tuple' object has no attribute '__module__'. Did you mean: '__mul__'?
```

**Comment by Ikaros-521** [comment]
change app.py `def update_visualization`
```
return fig, f"Graph visualization generated successfully. Using file: {graph_path}", config
```
->
```
return fig
```
