### ISSUE TITLE
Error in embedding_proxy.py 

### ISSUE THREAD

**Issue by havvk** [severian42/GraphRAG-Local-UI#75]
After running embedding proxy by embedding_proxy.py:
`python embedding_proxy.py --port 11435 --host http://localhost:11434`

I changed the  api_base parameter to embedding proxy in settings.yaml :
```
embeddings:
  async_mode: threaded # or asyncio
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    type: openai_embedding # or azure_openai_embedding
    model: nomic-embed-text:latest
    api_base: http://localhost:11435/v1

```
Then I tried to run indexing by the new index_app.py, it failed at the end stage.
```
2024-07-29 22:41:23,311 - api - INFO - ❌ create_final_community_reports
2024-07-29 22:41:23,311 - api - INFO - None
2024-07-29 22:41:23,324 - api - INFO - ⠋ GraphRAG Indexer
2024-07-29 22:41:23,324 - api - INFO - ├── Loading Input (InputFileType.text) - 1 files loaded (0 filtered) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
2024-07-29 22:41:23,324 - api - INFO - ├── create_base_text_units
2024-07-29 22:41:23,324 - api - INFO - ├── create_base_extracted_entities
2024-07-29 22:41:23,324 - api - INFO - ├── create_summarized_entities
2024-07-29 22:41:23,324 - api - INFO - ├── create_base_entity_graph
2024-07-29 22:41:23,324 - api - INFO - ├── create_final_entities
2024-07-29 22:41:23,324 - api - INFO - ├── create_final_nodes
2024-07-29 22:41:23,324 - api - INFO - ├── create_final_communities
2024-07-29 22:41:23,324 - api - INFO - ├── join_text_units_to_entity_ids
2024-07-29 22:41:23,324 - api - INFO - ├── create_final_relationships
2024-07-29 22:41:23,324 - api - INFO - ├── join_text_units_to_relationship_ids
2024-07-29 22:41:23,325 - api - INFO - └── create_final_community_reports❌ Errors occurred during the pipeline run, see logs for more details.
2024-07-29 22:41:23,361 - watchfiles.main - INFO - 1 change detected
2024-07-29 22:41:23,646 - api - ERROR - Indexing failed
```

There are some error in the embedding proxy:
```
INFO:     127.0.0.1:51300 - "POST /v1/embeddings HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/GraphRAG-Local-UI/embedding_proxy.py", line 44, in create_embedding
    total_tokens += result["usage"]["total_tokens"]
                    ~~~~~~^^^^^^^^^
KeyError: 'usage'
```

It seems there is no data of usage coming from Ollma (model: nomic-embed-text:latest).

**Comment by havvk** [comment]
https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings
As you can see , there is no usage data from Ollma Embeddings API:

**Request**
```
curl http://localhost:11434/api/embed -d '{
  "model": "all-minilm",
  "input": "Why is the sky blue?"
}'
```
**Response**
```
{
  "model": "all-minilm",
  "embeddings": [[
    0.010071029, -0.0017594862, 0.05007221, 0.04692972, 0.054916814,
    0.008599704, 0.105441414, -0.025878139, 0.12958129, 0.031952348
  ]]
}
```
**Request (Multiple input)**
```
curl http://localhost:11434/api/embed -d '{
  "model": "all-minilm",
  "input": ["Why is the sky blue?", "Why is the grass green?"]
}'
```
**Response**
```
{
  "model": "all-minilm",
  "embeddings": [[
    0.010071029, -0.0017594862, 0.05007221, 0.04692972, 0.054916814,
    0.008599704, 0.105441414, -0.025878139, 0.12958129, 0.031952348
  ],[
    -0.0098027075, 0.06042469, 0.025257962, -0.006364387, 0.07272725,
    0.017194884, 0.09032035, -0.051705178, 0.09951512, 0.09072481
  ]]
}
```

**Comment by wrench1997** [comment]
> After running embedding proxy by embedding_proxy.py: `python embedding_proxy.py --port 11435 --host http://localhost:11434`
> 
> I changed the api_base parameter to embedding proxy in settings.yaml :
> 
> ```
> embeddings:
>   async_mode: threaded # or asyncio
>   llm:
>     api_key: ${GRAPHRAG_API_KEY}
>     type: openai_embedding # or azure_openai_embedding
>     model: nomic-embed-text:latest
>     api_base: http://localhost:11435/v1
> ```
> 
> Then I tried to run indexing by the new index_app.py, it failed at the end stage.
> 
> ```
> 2024-07-29 22:41:23,311 - api - INFO - ❌ create_final_community_reports
> 2024-07-29 22:41:23,311 - api - INFO - None
> 2024-07-29 22:41:23,324 - api - INFO - ⠋ GraphRAG Indexer
> 2024-07-29 22:41:23,324 - api - INFO - ├── Loading Input (InputFileType.text) - 1 files loaded (0 filtered) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
> 2024-07-29 22:41:23,324 - api - INFO - ├── create_base_text_units
> 2024-07-29 22:41:23,324 - api - INFO - ├── create_base_extracted_entities
> 2024-07-29 22:41:23,324 - api - INFO - ├── create_summarized_entities
> 2024-07-29 22:41:23,324 - api - INFO - ├── create_base_entity_graph
> 2024-07-29 22:41:23,324 - api - INFO - ├── create_final_entities
> 2024-07-29 22:41:23,324 - api - INFO - ├── create_final_nodes
> 2024-07-29 22:41:23,324 - api - INFO - ├── create_final_communities
> 2024-07-29 22:41:23,324 - api - INFO - ├── join_text_units_to_entity_ids
> 2024-07-29 22:41:23,324 - api - INFO - ├── create_final_relationships
> 2024-07-29 22:41:23,324 - api - INFO - ├── join_text_units_to_relationship_ids
> 2024-07-29 22:41:23,325 - api - INFO - └── create_final_community_reports❌ Errors occurred during the pipeline run, see logs for more details.
> 2024-07-29 22:41:23,361 - watchfiles.main - INFO - 1 change detected
> 2024-07-29 22:41:23,646 - api - ERROR - Indexing failed
> ```
> 
> There are some errors in the embedding proxy:
> 
> ```
> INFO:     127.0.0.1:51300 - "POST /v1/embeddings HTTP/1.1" 500 Internal Server Error
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
>     result = await app(  # type: ignore[func-returns-value]
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
>     return await self.app(scope, receive, send)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
>     await super().__call__(scope, receive, send)
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
>     raise exc
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
>     await self.app(scope, receive, _send)
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
>     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
>     raise exc
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
>     await app(scope, receive, sender)
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
>     await route.handle(scope, receive, send)
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
>     await self.app(scope, receive, send)
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
>     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
>     raise exc
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
>     await app(scope, receive, sender)
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
>     response = await func(request)
>                ^^^^^^^^^^^^^^^^^^^
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
>     raw_response = await run_endpoint_function(
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/miniconda3/envs/graphrag/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
>     return await dependant.call(**values)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/GraphRAG-Local-UI/embedding_proxy.py", line 44, in create_embedding
>     total_tokens += result["usage"]["total_tokens"]
>                     ~~~~~~^^^^^^^^^
> KeyError: 'usage'
> ```
> 
> It seems there is no data of usage coming from Ollma (model: nomic-embed-text:latest).
My error is similar to yours, probably a format verification error
```
  return EmbeddingResponse(
      object="list",
      data=embeddings,
      model=request.model, 
      usage={},
  )
```

**Comment by JayWu890225** [comment]
when i use this command to query 'python3 -m graphrag.query --data ./indexing/output/20240802-172944/artifacts --method local --community_level 2 "What are the top themes in this story?"'

**Comment by sanzhar-rakhimkul** [comment]
@JayWu890225 Did you solve the problem ? I have same issue

**Comment by itcrazy0918** [comment]
i also have the problem like : HTTP Request: POST http://localhost:11435/embeddings "HTTP/1.1 404 Not Found"

**Comment by JayWu890225** [comment]
> @JayWu890225 Did you solve the problem ? I have same issue

actually i did not find root casue of this issue.

I changed some code in embed method - embedding.py.

        for chunk in token_chunks:
            try:
                embedding, chunk_len = self._embed_with_retry(text, **kwargs)
                chunk_embeddings.append(embedding)
                chunk_lens.append(chunk_len)

**Comment by sanzhar-rakhimkul** [comment]
> > @JayWu890225 Did you solve the problem ? I have same issue
> 
> actually i did not find root casue of this issue.
> 
> I changed some code in embed method - embedding.py.
> 
> ```
>     for chunk in token_chunks:
>         try:
>             embedding, chunk_len = self._embed_with_retry(text, **kwargs)
>             chunk_embeddings.append(embedding)
>             chunk_lens.append(chunk_len)
> ```

I found solution here
https://github.com/microsoft/graphrag/issues/451#issuecomment-2220861232
