### ISSUE TITLE
pip install -e ./graphrag时，报错不是一个git project

### ISSUE THREAD

**Issue by puluwen** [severian42/GraphRAG-Local-UI#85]
Installing build dependencies ... done
Checking if build backend supports build_editable ... done
Getting requirements to build editable ... done
Preparing editable metadata (pyproject.toml) ... error
error: subprocess-exited-with-error

× Preparing editable metadata (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [26 lines of output]
Traceback (most recent call last):
File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
main()
File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 181, in prepare_metadata_for_build_editable
return hook(metadata_directory, config_settings)
File "/tmp/pip-build-env-0pe1ibeo/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 42, in prepare_metadata_for_build_wheel
poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
File "/tmp/pip-build-env-0pe1ibeo/overlay/lib/python3.10/site-packages/poetry_dynamic_versioning/patch.py", line 26, in alt_poetry_create
name = _get_and_apply_version(
File "/tmp/pip-build-env-0pe1ibeo/overlay/lib/python3.10/site-packages/poetry_dynamic_versioning/__init__.py", line 705, in _get_and_apply_version
version, instance = _get_version(config, name)
File "/tmp/pip-build-env-0pe1ibeo/overlay/lib/python3.10/site-packages/poetry_dynamic_versioning/__init__.py", line 515, in _get_version
version = _get_version_from_dunamai(vcs, pattern, config)
File "/tmp/pip-build-env-0pe1ibeo/overlay/lib/python3.10/site-packages/poetry_dynamic_versioning/__init__.py", line 474, in _get_version_from_dunamai
return Version.from_vcs(
File "/tmp/pip-build-env-0pe1ibeo/overlay/lib/python3.10/site-packages/dunamai/__init__.py", line 2082, in from_vcs
return cls._do_vcs_callback(
File "/tmp/pip-build-env-0pe1ibeo/overlay/lib/python3.10/site-packages/dunamai/__init__.py", line 2137, in _do_vcs_callback
return callback(**kwargs)
File "/tmp/pip-build-env-0pe1ibeo/overlay/lib/python3.10/site-packages/dunamai/__init__.py", line 1096, in from_git
_detect_vcs(vcs, path)
File "/tmp/pip-build-env-0pe1ibeo/overlay/lib/python3.10/site-packages/dunamai/__init__.py", line 371, in _detect_vcs
raise RuntimeError("This does not appear to be a {} project".format(expected_vcs.value.title()))
RuntimeError: This does not appear to be a Git project
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by puluwen** [comment]
解决了，进入graphrag目录，先执行git init，再进行安装

**Comment by Egber1t** [comment]
> 解决了，进入graphrag目录，先执行git init，再进行安装

感谢
