### ISSUE TITLE
Error getting embeddings from nomic-embed-text:latest: 'data' ；getting Ollama embedding: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by francis123455** [severian42/GraphRAG-Local-UI#95]
09:34:41,980 root ERROR Error getting embeddings from nomic-embed-text:latest: 'data'
09:34:41,980 root INFO Falling back to Ollama embeddings
09:34:41,991 root ERROR Error getting Ollama embedding: [Errno 111] Connection refused
09:34:41,994 root ERROR Error getting Ollama embedding: [Errno 111] Connection refused
09:34:41,994 root ERROR Error getting Ollama embedding: [Errno 111] Connection refused
09:34:41,994 root ERROR Error getting Ollama embedding: [Errno 111] Connection refused
09:34:42,1 root ERROR Error getting Ollama embedding: [Errno 111] Connection refused
09:34:42,1 root ERROR Error getting Ollama embedding: [Errno 111] Connection refused
09:34:42,2 root ERROR Error getting Ollama embedding: [Errno 111] Connection refused
09:34:42,2 root ERROR Error getting Ollama embedding: [Errno 111] Connection refused
09:34:42,2 root ERROR Error getting Ollama embedding: [Errno 111] Connection refused
09:34:42,2 root ERROR Error getting Ollama embedding: [Errno 111] Connection refused
09:34:42,3 root ERROR Error getting Ollama embedding: [Errno 111] Connection refused
09:34:42,3 root ERROR Error getting Ollama embedding: [Errno 111] Connection refused
09:34:42,3 root ERROR Error getting Ollama embedding: [Errno 111] Connection refused
09:34:42,3 root ERROR Error getting Ollama embedding: [Errno 111] Connection refused
09:34:42,3 root ERROR Error getting Ollama embedding: [Errno 111] Connection refused
09:34:42,3 root ERROR Error getting Ollama embedding: [Errno 111] Connection refused
上述问题导致的下列报错怎么解决啊
09:34:42,239 graphrag.llm.base.rate_limiting_llm INFO perf - llm.embedding "Process" with 0 retries took 0.03099999949336052. input_tokens=305, output_tokens=0
09:34:42,239 datashaper.workflow.workflow ERROR Error executing verb "text_embed" in create_final_entities: list index out of range
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/graph-ollama-ui/lib/python3.10/site-packages/datashaper/workflow/workflow.py", line 415, in _execute_verb
    result = await result
  File "/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/verbs/text/embed/text_embed.py", line 105, in text_embed
    return await _text_embed_in_memory(
  File "/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/verbs/text/embed/text_embed.py", line 130, in _text_embed_in_memory
    result = await strategy_exec(texts, callbacks, cache, strategy_args)
  File "/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/verbs/text/embed/strategies/openai.py", line 62, in run
    embeddings = _reconstitute_embeddings(embeddings, input_sizes)
  File "/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/verbs/text/embed/strategies/openai.py", line 171, in _reconstitute_embeddings
    embedding = raw_embeddings[cursor]
IndexError: list index out of range
09:34:42,241 graphrag.index.reporting.file_workflow_callbacks INFO Error executing verb "text_embed" in create_final_entities: list index out of range details=None
09:34:42,241 root ERROR Error running workflow create_final_entities: list index out of range
09:34:42,437 graphrag.index.run INFO Running workflow: create_final_nodes...
09:34:42,437 graphrag.index.run INFO dependencies for create_final_nodes: ['create_base_entity_graph']
09:34:42,453 graphrag.index.run INFO read table from storage: create_base_entity_graph.parquet
09:34:42,526 datashaper.workflow.workflow INFO executing verb layout_graph
09:34:42,570 datashaper.workflow.workflow INFO executing verb unpack_graph
09:34:42,601 datashaper.workflow.workflow INFO executing verb unpack_graph
09:34:42,632 datashaper.workflow.workflow INFO executing verb filter
09:34:42,687 datashaper.workflow.workflow INFO executing verb drop
09:34:42,713 datashaper.workflow.workflow INFO executing verb select
09:34:42,739 datashaper.workflow.workflow INFO executing verb snapshot
09:34:42,767 datashaper.workflow.workflow INFO executing verb rename
09:34:42,794 datashaper.workflow.workflow INFO executing verb join
09:34:42,830 datashaper.workflow.workflow INFO executing verb convert
09:34:42,915 datashaper.workflow.workflow INFO executing verb rename
09:34:42,918 graphrag.index.emit.parquet_table_emitter INFO emitting parquet table create_final_nodes.parquet
09:34:43,175 graphrag.index.run INFO Running workflow: create_final_communities...
09:34:43,175 graphrag.index.run INFO dependencies for create_final_communities: ['create_base_entity_graph']
09:34:43,175 graphrag.index.run INFO read table from storage: create_base_entity_graph.parquet
09:34:43,238 datashaper.workflow.workflow INFO executing verb unpack_graph
09:34:43,272 datashaper.workflow.workflow INFO executing verb unpack_graph
09:34:43,307 datashaper.workflow.workflow INFO executing verb aggregate_override
09:34:43,340 datashaper.workflow.workflow INFO executing verb join
09:34:43,379 datashaper.workflow.workflow INFO executing verb join
09:34:43,418 datashaper.workflow.workflow INFO executing verb concat
09:34:43,450 datashaper.workflow.workflow INFO executing verb filter
09:34:43,578 datashaper.workflow.workflow INFO executing verb aggregate_override
09:34:43,614 datashaper.workflow.workflow INFO executing verb join
09:34:43,655 datashaper.workflow.workflow INFO executing verb filter
09:34:43,728 datashaper.workflow.workflow INFO executing verb fill
09:34:43,761 datashaper.workflow.workflow INFO executing verb merge
09:34:43,796 datashaper.workflow.workflow INFO executing verb copy
09:34:43,830 datashaper.workflow.workflow INFO executing verb select
09:34:43,833 graphrag.index.emit.parquet_table_emitter INFO emitting parquet table create_final_communities.parquet
09:34:44,86 graphrag.index.run INFO Running workflow: join_text_units_to_entity_ids...
09:34:44,86 graphrag.index.run INFO dependencies for join_text_units_to_entity_ids: ['create_final_entities']
09:34:44,86 graphrag.index.run ERROR error running workflow join_text_units_to_entity_ids
Traceback (most recent call last):
  File "/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/run.py", line 320, in run_pipeline
    await inject_workflow_data_dependencies(workflow)
  File "/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/run.py", line 256, in inject_workflow_data_dependencies
    table = await load_table_from_storage(f"{id}.parquet")
  File "/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/run.py", line 242, in load_table_from_storage
    raise ValueError(msg)
ValueError: Could not find create_final_entities.parquet in storage!
09:34:44,87 graphrag.index.reporting.file_workflow_callbacks INFO Error running pipeline! details=None

**Comment by francis123455** [comment]
我是因为改了ollama的端口，改回去就好了
